### PR TITLE
composer: sniffer is a dependency

### PR DESCRIPTION
**Pull request by TomasVotruba**
It common to add sniffer as dependency, since rules itself depends on specific version of sniffer.
Moreover while extending them. This package would not work with version 1.0, although it's allowed.

This should fix it and also simplifies the install.

### CODE REVIEW

**Comment by vysinsky** [comment]
Thanks! I think you can update also readme according to `This should fix it and also simplifies the install.`

**Comment by vysinsky** [comment]
> This package would not work with version 1.0, although it's allowed.

What do you mean by version 1.0?

**Comment by TomasVotruba** [comment]
> Thanks! I think you can update also readme according to This should fix it and also simplifies the install.

I'm on it!

> What do you mean by version 1.0?

I meant Php_CodeSniffer 1.0 (e.g.)

**Comment by TomasVotruba** [comment]
Btw, what about adding package to packagist and make installation one-liner?

```sh
composer require squizlabs/php_codesniffer --dev
```

This 3 step is really discouraging. What's the intention behind it?

**Comment by vysinsky** [comment]
We didn't want to make it public. But I will discuss it with my colleagues.

**Comment by TomasVotruba** [comment]
Public in what way? It's public already in here.

**Comment by vysinsky** [comment]
Publicly visible on packagist :) I think we could add it there, but decision is not only on me.

**Comment by TomasVotruba** [comment]
I use it in Zenify [like this](https://github.com/Zenify/CodingStandard#install). Much user-friendly, mainly for starters with PHP_CodeSniffer, who complex already.

**Comment by TomasVotruba** [comment]
Interesting, I see.

**Comment by vojtech-dobes** [comment]
I would say the reason for not having on Packagist was simply because it was in no way finished and meant to be used by other people, because it was probably full of bugs and problems - that is documented by line of `Excluded...` commits :). We made it public because why not and why waste private repository slot for it :).

Reason why haven't made Codesniffer itself dependency was to make requiring it explicitly a necessary step. This is only ruleset, it doesn't come with Codesniffer included. That's the reasoning I would say.

**Comment by TomasVotruba** [comment]
I see, now it makes sense. I use Gitlab for these, that's why it seemed to strange to make it public just a little.

As for version, I understand it's only ruleset. In logic it makes sense, but it contains code that depends on something that's missing. The installation should depend only on composer definitions, not README (dry).

Also as I stated, these sniffs depends on specific version of PHP_CodeSniffer. Someone might have version 1, somebody else 2 and soon 3 will be out. Already got some BC breaks even between version 2.0 and 2.2. That's why suggest locking to specific version, to prevent possible breaking.

Feel free to close/merge.

**Comment by TomasVotruba** [comment]
Close due to no response timeout.

**Pull request closed without merging**
